# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\py34\gui\mm3_add_person.ui',
# licensing of 'C:\py34\gui\mm3_add_person.ui' applies.
#
# Created: Sun Oct  6 10:12:33 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(938, 591)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_FIO = QtWidgets.QLabel(self.tab)
        self.label_FIO.setGeometry(QtCore.QRect(10, 50, 47, 16))
        self.label_FIO.setObjectName("label_FIO")
        self.lineEdit_FIO = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_FIO.setGeometry(QtCore.QRect(10, 70, 361, 20))
        self.lineEdit_FIO.setObjectName("lineEdit_FIO")
        self.label_data_born = QtWidgets.QLabel(self.tab)
        self.label_data_born.setGeometry(QtCore.QRect(10, 110, 151, 16))
        self.label_data_born.setObjectName("label_data_born")
        self.dateEdit_data_born = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_data_born.setGeometry(QtCore.QRect(10, 130, 101, 22))
        self.dateEdit_data_born.setWrapping(False)
        self.dateEdit_data_born.setFrame(True)
        self.dateEdit_data_born.setReadOnly(False)
        self.dateEdit_data_born.setKeyboardTracking(True)
        self.dateEdit_data_born.setProperty("showGroupSeparator", False)
        self.dateEdit_data_born.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_data_born.setCalendarPopup(True)
        self.dateEdit_data_born.setCurrentSectionIndex(0)
        self.dateEdit_data_born.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_data_born.setObjectName("dateEdit_data_born")
        self.label_IIN = QtWidgets.QLabel(self.tab)
        self.label_IIN.setGeometry(QtCore.QRect(10, 170, 47, 21))
        self.label_IIN.setObjectName("label_IIN")
        self.lineEdit_IIN = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_IIN.setGeometry(QtCore.QRect(10, 190, 171, 20))
        self.lineEdit_IIN.setObjectName("lineEdit_IIN")
        self.label_organiz = QtWidgets.QLabel(self.tab)
        self.label_organiz.setGeometry(QtCore.QRect(10, 230, 71, 16))
        self.label_organiz.setObjectName("label_organiz")
        self.lineEdit_organiz = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_organiz.setGeometry(QtCore.QRect(10, 250, 171, 20))
        self.lineEdit_organiz.setObjectName("lineEdit_organiz")
        self.groupBox_zp_os = QtWidgets.QGroupBox(self.tab)
        self.groupBox_zp_os.setGeometry(QtCore.QRect(10, 290, 271, 151))
        self.groupBox_zp_os.setCheckable(True)
        self.groupBox_zp_os.setObjectName("groupBox_zp_os")
        self.label_dolzhnost = QtWidgets.QLabel(self.groupBox_zp_os)
        self.label_dolzhnost.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_dolzhnost.setObjectName("label_dolzhnost")
        self.lineEdit_dolzhnost = QtWidgets.QLineEdit(self.groupBox_zp_os)
        self.lineEdit_dolzhnost.setGeometry(QtCore.QRect(80, 20, 151, 20))
        self.lineEdit_dolzhnost.setObjectName("lineEdit_dolzhnost")
        self.label_stavka = QtWidgets.QLabel(self.groupBox_zp_os)
        self.label_stavka.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_stavka.setObjectName("label_stavka")
        self.lineEdit_stavka = QtWidgets.QLineEdit(self.groupBox_zp_os)
        self.lineEdit_stavka.setGeometry(QtCore.QRect(80, 80, 151, 20))
        self.lineEdit_stavka.setObjectName("lineEdit_stavka")
        self.label_summa = QtWidgets.QLabel(self.groupBox_zp_os)
        self.label_summa.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_summa.setObjectName("label_summa")
        self.lineEdit_summa = QtWidgets.QLineEdit(self.groupBox_zp_os)
        self.lineEdit_summa.setGeometry(QtCore.QRect(80, 110, 151, 20))
        self.lineEdit_summa.setObjectName("lineEdit_summa")
        self.label_koeff = QtWidgets.QLabel(self.groupBox_zp_os)
        self.label_koeff.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_koeff.setObjectName("label_koeff")
        self.lineEdit_koeff = QtWidgets.QLineEdit(self.groupBox_zp_os)
        self.lineEdit_koeff.setGeometry(QtCore.QRect(80, 50, 151, 20))
        self.lineEdit_koeff.setObjectName("lineEdit_koeff")
        self.groupBox_zp_dop_1 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_zp_dop_1.setGeometry(QtCore.QRect(310, 290, 271, 151))
        self.groupBox_zp_dop_1.setCheckable(True)
        self.groupBox_zp_dop_1.setChecked(False)
        self.groupBox_zp_dop_1.setObjectName("groupBox_zp_dop_1")
        self.label_dop1_dolzh = QtWidgets.QLabel(self.groupBox_zp_dop_1)
        self.label_dop1_dolzh.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_dop1_dolzh.setObjectName("label_dop1_dolzh")
        self.lineEdit_dop1_dolzh = QtWidgets.QLineEdit(self.groupBox_zp_dop_1)
        self.lineEdit_dop1_dolzh.setGeometry(QtCore.QRect(80, 20, 151, 20))
        self.lineEdit_dop1_dolzh.setObjectName("lineEdit_dop1_dolzh")
        self.label_dop1_stavka = QtWidgets.QLabel(self.groupBox_zp_dop_1)
        self.label_dop1_stavka.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_dop1_stavka.setObjectName("label_dop1_stavka")
        self.lineEdit_dop1_stavka = QtWidgets.QLineEdit(self.groupBox_zp_dop_1)
        self.lineEdit_dop1_stavka.setGeometry(QtCore.QRect(80, 80, 151, 20))
        self.lineEdit_dop1_stavka.setObjectName("lineEdit_dop1_stavka")
        self.label_dop1_summa = QtWidgets.QLabel(self.groupBox_zp_dop_1)
        self.label_dop1_summa.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_dop1_summa.setObjectName("label_dop1_summa")
        self.lineEdit_dop1_summa = QtWidgets.QLineEdit(self.groupBox_zp_dop_1)
        self.lineEdit_dop1_summa.setGeometry(QtCore.QRect(80, 110, 151, 20))
        self.lineEdit_dop1_summa.setObjectName("lineEdit_dop1_summa")
        self.label_dop1_koeff = QtWidgets.QLabel(self.groupBox_zp_dop_1)
        self.label_dop1_koeff.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_dop1_koeff.setObjectName("label_dop1_koeff")
        self.lineEdit_dop1_koeff = QtWidgets.QLineEdit(self.groupBox_zp_dop_1)
        self.lineEdit_dop1_koeff.setGeometry(QtCore.QRect(80, 50, 151, 20))
        self.lineEdit_dop1_koeff.setObjectName("lineEdit_dop1_koeff")
        self.groupBox_zp_dop_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_zp_dop_2.setGeometry(QtCore.QRect(610, 290, 271, 151))
        self.groupBox_zp_dop_2.setCheckable(True)
        self.groupBox_zp_dop_2.setChecked(False)
        self.groupBox_zp_dop_2.setObjectName("groupBox_zp_dop_2")
        self.label_dop2_dolzh = QtWidgets.QLabel(self.groupBox_zp_dop_2)
        self.label_dop2_dolzh.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_dop2_dolzh.setObjectName("label_dop2_dolzh")
        self.lineEdit_dop2_dolzh = QtWidgets.QLineEdit(self.groupBox_zp_dop_2)
        self.lineEdit_dop2_dolzh.setGeometry(QtCore.QRect(80, 20, 151, 20))
        self.lineEdit_dop2_dolzh.setObjectName("lineEdit_dop2_dolzh")
        self.label_dop2_stavka = QtWidgets.QLabel(self.groupBox_zp_dop_2)
        self.label_dop2_stavka.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_dop2_stavka.setObjectName("label_dop2_stavka")
        self.lineEdit_dop2_stavka = QtWidgets.QLineEdit(self.groupBox_zp_dop_2)
        self.lineEdit_dop2_stavka.setGeometry(QtCore.QRect(80, 80, 151, 20))
        self.lineEdit_dop2_stavka.setObjectName("lineEdit_dop2_stavka")
        self.label_dop2_summa = QtWidgets.QLabel(self.groupBox_zp_dop_2)
        self.label_dop2_summa.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_dop2_summa.setObjectName("label_dop2_summa")
        self.lineEdit_dop2_summa = QtWidgets.QLineEdit(self.groupBox_zp_dop_2)
        self.lineEdit_dop2_summa.setGeometry(QtCore.QRect(80, 110, 151, 20))
        self.lineEdit_dop2_summa.setObjectName("lineEdit_dop2_summa")
        self.label_dop2_koeff = QtWidgets.QLabel(self.groupBox_zp_dop_2)
        self.label_dop2_koeff.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_dop2_koeff.setObjectName("label_dop2_koeff")
        self.lineEdit_dop2_koeff = QtWidgets.QLineEdit(self.groupBox_zp_dop_2)
        self.lineEdit_dop2_koeff.setGeometry(QtCore.QRect(80, 50, 151, 20))
        self.lineEdit_dop2_koeff.setObjectName("lineEdit_dop2_koeff")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_ID.setEnabled(False)
        self.lineEdit_ID.setGeometry(QtCore.QRect(120, 10, 111, 20))
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.label_ID = QtWidgets.QLabel(self.tab)
        self.label_ID.setGeometry(QtCore.QRect(16, 10, 83, 21))
        self.label_ID.setObjectName("label_ID")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.btn_save = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(742, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.btn_cancle = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_cancle.setFont(font)
        self.btn_cancle.setObjectName("btn_cancle")
        self.gridLayout.addWidget(self.btn_cancle, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_FIO, self.dateEdit_data_born)
        Form.setTabOrder(self.dateEdit_data_born, self.lineEdit_IIN)
        Form.setTabOrder(self.lineEdit_IIN, self.lineEdit_organiz)
        Form.setTabOrder(self.lineEdit_organiz, self.groupBox_zp_os)
        Form.setTabOrder(self.groupBox_zp_os, self.lineEdit_dolzhnost)
        Form.setTabOrder(self.lineEdit_dolzhnost, self.lineEdit_koeff)
        Form.setTabOrder(self.lineEdit_koeff, self.lineEdit_stavka)
        Form.setTabOrder(self.lineEdit_stavka, self.lineEdit_summa)
        Form.setTabOrder(self.lineEdit_summa, self.groupBox_zp_dop_1)
        Form.setTabOrder(self.groupBox_zp_dop_1, self.lineEdit_dop1_dolzh)
        Form.setTabOrder(self.lineEdit_dop1_dolzh, self.lineEdit_dop1_koeff)
        Form.setTabOrder(self.lineEdit_dop1_koeff, self.lineEdit_dop1_stavka)
        Form.setTabOrder(self.lineEdit_dop1_stavka, self.lineEdit_dop1_summa)
        Form.setTabOrder(self.lineEdit_dop1_summa, self.groupBox_zp_dop_2)
        Form.setTabOrder(self.groupBox_zp_dop_2, self.lineEdit_dop2_dolzh)
        Form.setTabOrder(self.lineEdit_dop2_dolzh, self.lineEdit_dop2_koeff)
        Form.setTabOrder(self.lineEdit_dop2_koeff, self.lineEdit_dop2_stavka)
        Form.setTabOrder(self.lineEdit_dop2_stavka, self.lineEdit_dop2_summa)
        Form.setTabOrder(self.lineEdit_dop2_summa, self.btn_save)
        Form.setTabOrder(self.btn_save, self.btn_cancle)
        Form.setTabOrder(self.btn_cancle, self.tabWidget)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_FIO.setText(QtWidgets.QApplication.translate("Form", "ФИО", None, -1))
        self.label_data_born.setText(QtWidgets.QApplication.translate("Form", "Дата рождения", None, -1))
        self.label_IIN.setText(QtWidgets.QApplication.translate("Form", "ИИН", None, -1))
        self.label_organiz.setText(QtWidgets.QApplication.translate("Form", "Организация", None, -1))
        self.groupBox_zp_os.setTitle(QtWidgets.QApplication.translate("Form", "Основная зарплата", None, -1))
        self.label_dolzhnost.setText(QtWidgets.QApplication.translate("Form", "Должность", None, -1))
        self.label_stavka.setText(QtWidgets.QApplication.translate("Form", "Ставка", None, -1))
        self.label_summa.setText(QtWidgets.QApplication.translate("Form", "Сумма", None, -1))
        self.label_koeff.setText(QtWidgets.QApplication.translate("Form", "Коэф/т", None, -1))
        self.groupBox_zp_dop_1.setTitle(QtWidgets.QApplication.translate("Form", "Дополнительная зарплата-1", None, -1))
        self.label_dop1_dolzh.setText(QtWidgets.QApplication.translate("Form", "Должность", None, -1))
        self.label_dop1_stavka.setText(QtWidgets.QApplication.translate("Form", "Ставка", None, -1))
        self.label_dop1_summa.setText(QtWidgets.QApplication.translate("Form", "Сумма", None, -1))
        self.label_dop1_koeff.setText(QtWidgets.QApplication.translate("Form", "Коэф/т", None, -1))
        self.groupBox_zp_dop_2.setTitle(QtWidgets.QApplication.translate("Form", "Дополнительная зарплата-2", None, -1))
        self.label_dop2_dolzh.setText(QtWidgets.QApplication.translate("Form", "Должность", None, -1))
        self.label_dop2_stavka.setText(QtWidgets.QApplication.translate("Form", "Ставка", None, -1))
        self.label_dop2_summa.setText(QtWidgets.QApplication.translate("Form", "Сумма", None, -1))
        self.label_dop2_koeff.setText(QtWidgets.QApplication.translate("Form", "Коэф/т", None, -1))
        self.label_ID.setText(QtWidgets.QApplication.translate("Form", "Номер в системе", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("Form", "Данные", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Form", "Банковские данные", None, -1))
        self.btn_save.setText(QtWidgets.QApplication.translate("Form", "Сохранить", None, -1))
        self.btn_cancle.setText(QtWidgets.QApplication.translate("Form", "Отмена", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

